# Generated by Django 4.2.3 on 2023-07-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
